// <auto-generated />
using CityInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo.API.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    [Migration("20220728170533_DataSeed")]
    partial class DataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The city of love and baguette.",
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fish and Chips all day long.",
                            Name = "London"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The Big Apple just a mouth away.",
                            Name = "New York"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointsOfInterest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "The Famous Museum in Paris.",
                            Name = "Louvre"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "The Famous Metallic Tower of Paris.",
                            Name = "Eiffel Tower"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "The wheel of South Bank.",
                            Name = "The Big Eye"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "The striking clock of the Palace of Westminster.",
                            Name = "The Big Ben"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "The most famous theatre in the world.",
                            Name = "Broadway Theatre"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Description = "A square full of lights which the fame came from.",
                            Name = "Madison Square"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.HasOne("CityInfo.API.Entities.City", "City")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Navigation("PointsOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
